In [2]:
import numpy as np
import pandas as pd

In [20]:
# 1. Create a null vector of size 10 but the fifth value which is 1.

# Method 1:
null_vector1 = np.array([np.nan,np.nan,np.nan,np.nan,1,np.nan,np.nan,np.nan,np.nan,np.nan])
print(null_vector1)

print('-'*40)

# Method 2:
null_vector2 = np.zeros(10, dtype=int)
null_vector2[4] = 1
null_vector2

[nan nan nan nan  1. nan nan nan nan nan]
----------------------------------------


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
# 2. Create a vector with values ranging from 10 to 49.

vectr = np.arange(10,50)
vectr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
matrix_vals = np.arange(9).reshape(3,3)

matrix_vals

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

input_arr = np.array([1,2,0,0,4,0])
np.nonzero(input_arr)

(array([0, 1, 4]),)

In [16]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
arr = np.random.rand(10,10)
print(arr)
print(arr.max())
print(arr.min())

[[0.3126346  0.97175089 0.11189055 0.3310344  0.93378649 0.1635213
  0.87271022 0.02586406 0.61848205 0.46440012]
 [0.19465922 0.99149584 0.33636158 0.44162623 0.09090207 0.68327415
  0.54722815 0.12066123 0.36272299 0.15928558]
 [0.37357245 0.74731199 0.7726118  0.69022119 0.76655978 0.81976152
  0.95844654 0.346192   0.78136388 0.89158949]
 [0.17255539 0.65886952 0.4098469  0.97042003 0.50390432 0.32966662
  0.52123267 0.67300099 0.71486796 0.92531016]
 [0.93935528 0.85489351 0.52855764 0.35759419 0.69884274 0.09149073
  0.40278345 0.8969854  0.61798174 0.46770771]
 [0.26939097 0.3001735  0.39299659 0.20544676 0.39118319 0.05974187
  0.2429749  0.28423479 0.85020182 0.50776894]
 [0.80621894 0.47766877 0.32598416 0.52587363 0.02756893 0.82283537
  0.76461629 0.14125177 0.82102249 0.54899528]
 [0.13998827 0.3070448  0.21622828 0.3753072  0.75751578 0.03941652
  0.60663228 0.70341193 0.6332626  0.54644035]
 [0.76417649 0.37526861 0.88158997 0.18232696 0.58034575 0.928641
  0.97115646 0.

In [17]:
# 6. Create a random vector of size 30 and find the mean value.

arr2 = np.random.rand(30)

print(arr2)
print(arr2.mean())

[0.50546408 0.3054881  0.45407968 0.54315254 0.28003638 0.88455678
 0.3803553  0.39479698 0.08164832 0.85937653 0.91146411 0.52458948
 0.16508846 0.0884375  0.52687423 0.25340534 0.73414111 0.91364806
 0.56028348 0.75092823 0.95716231 0.48223222 0.21371468 0.2174967
 0.63983821 0.55012007 0.7145337  0.57122318 0.60728659 0.34546779]
0.5138963383329457
